### ISSUE TITLE
Binder is broken

### ISSUE THREAD

**Issue by FrancoisPgm** [PSY3018/psy3018.github.io#43]
ERROR: Could not find a version that satisfies the requirement image-io>=2.9.0 (from versions: 0.0.1, 1.0.0, 1.1.1, 1.2.0, 1.3.0, 1.4.0, 1.4.1, 1.4.2, 1.5.0)
ERROR: No matching distribution found for image-io>=2.9.0

**Comment by pbellec** [comment]
should be fixed now, thanks for catching it!
